### PR TITLE
Added missing facility constants from RFC3164, part 4.1.1

### LINKED ISSUE #2: Not all Syslog FACILITY levels can be specified
[SyslogConstants.java](https://github.com/Graylog2/syslog4j-graylog2/blob/24daa908bcf37bda0e6487d9b5e2ed25a62323e8/src/main/java/org/graylog2/syslog4j/SyslogConstants.java):

The following Facility level constants are missing and therefore cannot be specified:

          12             NTP subsystem
          13             log audit (note 1)
          14             log alert (note 1)
          15             clock daemon (note 2)

See [RFC3164, 4.1.1 PRI Part](https://tools.ietf.org/html/rfc3164#section-4.1.1). This means that currently not all facility levels can be specified for sending a message.

### PR DESCRIPTION
**Pull request by dfch**
* This pull request adds the missing constants from RFC3164, part 4.1.1
* In addition, I did some "fixes" on `getFacility` and `getSeverity` (redundant / inconsistent code)
* I added unit tests for the newly added syslog facilities
* This would resolve #2

### CODE REVIEW

**Comment by joschi** [comment]
Thanks for this PR! In order to continue, we need you to sign the Graylog Contributor Agreement: https://www.graylog.org/contributing-to-graylog/

**Comment by dfch** [comment]
@joschi I filled out and sent you the signed Contributor Agreement via mail to your contributor alias.

**Comment by lennartkoopmann** [comment]
Thanks! I confirm that we received the signed CLA.

**Comment by joschi** [comment]
PR looks good to me (even with tests :heart:). Thanks @dfch!

**Pull request merged**
